spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.120.20:8848
    alicloud:
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5


  application:
    name: gulimall-third-party

server:
  port: 30000